mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('wiki/', include('wiki.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wiki/urls.py
from django.urls import path, re_path
from . import views

app_name = 'wiki'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    re_path(r'^Register/', views.register_page, name='register'),
    re_path(r'^Login/', views.WikiLoginView.as_view(), name='login'),
    re_path(r'^Logout/', views.WikiLogoutView.as_view(), name='logout'),
    re_path(r'^Upload/', views.upload_file, name='upload'),
    path('Delete/<int:pk>/', views.delete_file, name='delete'),
    path('<str:pk>/', views.PageView.as_view(), name='pageview'),
    path('<str:pk>/edit/', views.EditView.as_view(), name='edit'),
]

wiki/models.py
from django.db import models
import os
from django.conf import settings

# Create your models here.

class Page(models.Model):
    page_name = models.CharField(max_length=60, primary_key=True)
    page_content = models.TextField()
    page_counter = models.IntegerField(default=1)

    def inchits(self):
        self.page_counter += 1
        self.save()

    def __str__(self):
        return self.page_name

    def get_absolute_url(self):
        pass

class UserFile(models.Model):
    content = models.FileField(upload_to='uploads/')

    def __str__(self):
        return self.content.name

    def get_absolute_url(self):
        return self.content.url

    def delete(self, *args, **kwargs):
        dir = os.path.dirname(os.path.join(settings.MEDIA_ROOT, self.content.name))
        try:
            self.content.delete()
        except OSError:
            pass
        try:
            os.rmdir(dir)
        except OSError:
            pass
        return models.Model.delete(self)
        #print('Deleting {0}'.format(self.content.name))
        #super().delete(self)

wiki/forms.py
from django.forms import ModelForm
from .models import UserFile

class FileUploadForm(ModelForm):
    class Meta:
        model = UserFile
        fields = '__all__'

wiki/views.py
# Required imports
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.http.response import Http404
from .models import Page, UserFile
from .forms import FileUploadForm
from django.contrib.auth import views as auth_views, login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from os.path import split

def register_page(request):
    '''Function-based view for user registration'''

    # If the user got here via POST:
    if request.method == 'POST':
        # Create a variable containing a UserCreationForm with the content of the POST.
        form = UserCreationForm(request.POST)
        # If the form variable is valid:
        if form.is_valid():
            # Create username and password variables containing cleaned data of the entered username and password,
            # where 'cleaned data' ensures the data is the correct type (in this case, strings).
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            # Create a variable containing a user creation with the credentials provided by the user:
            user = User.objects.create_user(username=username, password=password)
            # Save the user and therefore store it in the database:
            user.save()
            # Authenticate the user:
            user = authenticate(request, username=username, password=password)
            # Log the user in:
            login(request, user)
            # Then, redirect to the index with the user now registered and logged in.
            return redirect('wiki:index')
    # Else, if the user did not arrive via POST:
    else:
    # Create a variable containing a UserCreationForm with no added content:
        form = UserCreationForm()
    # Then, render the 'create_user' template with the content of the form.
    return render(request, 'wiki/create_user.html', {'form': form})


class WikiLoginView(auth_views.LoginView):
    '''Class-based view for logging in'''

    # Modifies the 'get_context_data' method as follows:
    def get_context_data(self, **kwargs):
        # Defines a variable containing all context data
        context = super().get_context_data(**kwargs)
        # If the user is authenticated:
        if self.request.user.is_authenticated:
            # Set an 'auth' context to 'auth':
            context['auth'] = 'auth'
        # Then, return the context.
        return context

    # Points to the correct template
    template_name = 'wiki/login.html'


class WikiLogoutView(auth_views.LogoutView):
    '''Class-based view for logging out'''

    def get_next_page(self):
        return reverse('wiki:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['auth'] = 'auth'
        return context


class IndexView(generic.ListView):
    '''Class-based view for the index'''

    # Points to the correct template
    template_name = 'wiki/index.html'
    # Defines a context object name for reference in the 'index' template
    context_object_name = 'pages'
    # Modifies the 'get_queryset' method to return all pages, ordered by page name
    def get_queryset(self):
        return Page.objects.all().order_by('page_name')
    # Modifies the 'get_context_data' method as follows:
    def get_context_data(self, **kwargs):
        # Defines a variable containing all context data
        context = super().get_context_data(**kwargs)
        # Defines a 'client' context with a request for displaying browser data
        context['client'] = self.request.META['HTTP_USER_AGENT']
        # If the user is authenticated:
        if self.request.user.is_authenticated:
            # Set an 'auth' context to 'auth':
            context['auth'] = 'auth'
        # Then, return the context.
        return context


class PageView(generic.DetailView):
    '''Class-based view for pages'''

    # Retrieves the correct model
    model = Page
    # Points to the correct template
    template_name = 'wiki/page.html'
    # Defines a context object name for reference in the 'page' template
    context_object_name = 'this_page'
    # Modifies the 'get_context_data' method as follows:
    def get_context_data(self, **kwargs):
        # Defines a variable containing all context data
        context = super().get_context_data(**kwargs)
        # If the user is authenticated,
        if self.request.user.is_authenticated:
            # set an 'auth' context to 'auth':
            context['auth'] = 'auth'
        # then, return the context.
        return context
    # Modifies the 'get' method as follows:
    def get(self, request, *args, **kwargs):
        # Attempts to retrieve the given page's object. If the 'try' is unsuccessful, the page's object does not currently exist.
        try:
            self.object = self.get_object()
            self.object.inchits()
        # If the Http404 exception is thrown, redirect to the edit page of the new page
        except Http404:
            return redirect('wiki:edit', pk=self.kwargs['pk'])
        # If the 'try' was successful, the context data is set to the page's object:
        context = self.get_context_data(object=self.object)
        # Then, this page's object is rendered into the page template
        return render(request, self.template_name, context)


class EditView(LoginRequiredMixin, generic.DetailView):
    '''Class-based view for editing pages'''

    login_url = reverse_lazy('wiki:login')
    # Retrieves the correct model
    model = Page
    # Points to the correct template
    template_name = 'wiki/edit.html'
    # Defines a context object name for reference in the 'edit' template
    context_object_name='page'
    # Modifies the 'post' method as follows:
    def post(self, request, *args, **kwargs):
        # Defines a variable containing the primary key of the page
        prim_key = self.kwargs['pk']
        # If the user got here via POSTing a save to the page:
        if 'Save' in request.POST:
            # Define a variable containing the tuple of retrieving the page object, or creating it if it does not exist:
            page, _ = Page.objects.get_or_create(page_name=prim_key)
            # Set the page content to the 'pagecontent' key value:
            page.page_content = request.POST['pagecontent']
            # Save the page changes:
            page.save()
            # Redirect to the given page, using its primary key
            return redirect('wiki:pageview', pk=prim_key)
        # Else, if the user did not get here via POSTing a save to the page, try retrieving the page's object and redirect to it
        else:
            try:
                page = Page.objects.get(pk=prim_key)
                return redirect('wiki:pageview', pk=prim_key)
            # If the DoesNotExist exception is thrown, redirect to the index
            except Page.DoesNotExist:
                return redirect('wiki:index')
    #Modifies the 'get' method as follows:
    def get(self, request, *args, **kwargs):
        # Defines a variable containing the primary key of the page
        prim_key = self.kwargs['pk']
        # Try retrieving the page's object
        try:
            page = Page.objects.get(page_name=prim_key)
        # If the DoesNotExist exception is thrown, the page []
        except Page.DoesNotExist:
            page = Page(prim_key)
        # Render the edit view with the page content
        return render(request, 'wiki/edit.html', {'page': page})

    # Modifies the 'get_context_data' method as follows:
    def get_context_data(self, **kwargs):
        # Defines a variable containing all context data
        context = super().get_context_data(**kwargs)
        # If the user is authenticated,
        if self.request.user.is_authenticated:
            # set the context to []:
            context['auth'] = 'auth'
        # then, return the context.
        return context

def upload_file(request):
    '''Function for file upload functionality. Determines if a request has been POSTed
    and sends the provided data (i.e. the file) to the form.'''

    if request.method == 'POST':
        form = FileUploadForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
    else:
        form = FileUploadForm()
    context = {}
    context['form'] = form
    context['files'] = UserFile.objects.all().order_by('content')
    for f in context['files']:
        f.displayname = split(f.content.name)[1]

    return render(request, 'wiki/upload.html', context)

def delete_file(request, pk):
    '''Function that deletes files based on the primary key of the request.'''

    UserFile.objects.get(pk=pk).delete()
    return redirect('wiki:upload')

wiki/templates/wiki/base.html
<!-- Retrieving static files for website customisation -->
{% load static %}
<!-- Specifying type of document and HTML language -->
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'wiki/css/styles.css' %}">
        <!-- Block for custom CSS that is overridden in necessary inheriting pages -->
        {% block pageCustom %}

        {% endblock pageCustom %}
        <!-- Block for page title that is overridden in all inheriting pages -->
        {% block title %}
        <title>BasePageTitle</title>
        {% endblock title %}
    </head>
    <body>
        <nav class="navbar justify-content-between navbar-expand-lg navbar-light bg-light">
            <div class="navbar-brand">
                <a class="nav-item nav-link" href="{% url 'wiki:index' %}">Index</a>
            </div>
            <div>
                {% block navItem %}

                {% endblock navItem %}
            </div>
            <div>
                <!-- Block for page login that is overridden in necessary inheriting pages -->
                {% block login %}

                {% endblock login %}
            </div>
        </nav>

        <!-- Block for page content that is overridden in all inheriting pages -->
        {% block content %}

            Base text.

        {% endblock content %}
        <!-- If client data is available, display a footer containing the user's browser information -->
        {% if client %}
            <footer class="footer">{{ client }}</footer>
        {% endif %}

        <!-- Block for custom scripts that is overridden in necessary inheriting pages -->
        {% block pageCustomScripts %}

        {% endblock pageCustomScripts %}
        <!-- Optional JavaScript-->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

    </body>
</html>

wiki/templates/wiki/create_user.html
<!-- Extends the base template -->
{% extends 'wiki/base.html' %}
<!-- Overrides the base title block with the create user title -->
{% block title %}<title>Create User</title>{% endblock title %}
<!-- Overrides the base content block to display a registration form -->
{% block content %}
    <!-- If the user encounters an error with the form, notify them to try again -->
    {% if form.errors %}
        <p>There was an error on the form. Please try again.</p>
    {% endif %}
    <form class="form-registration" method="post" action="{% url 'wiki:register' %}">
        <!-- Required CSRF token for security purposes -->
        {% csrf_token %}
        <!-- Displays the form content -->
        {{ form }}
        <!-- Submit button for user creation -->
        <button class="btn btn-danger" type="submit">Create User</button>
    </form>

{% endblock content %}
<!-- Overrides the base login block to add login/logout buttons -->
{% block login %}
    <!-- 'auth' determines if the user is authenticated; so, if the user is not, the 'login' nav is displayed -->
    {% if not auth %}
        <nav><a href="{% url 'wiki:login' %}" class="btn btn-primary m-2">Login</a></nav>
    <!-- Else, if the user is authenticated, display the logout button -->
    {% else %}
        <nav><a href="{% url 'wiki:logout' %}" class="btn btn-danger m-2">Logout</a></nav>
    {% endif %}

{% endblock login %}

wiki/templates/wiki/edit.html
<!-- Extends the base template -->
{% extends 'wiki/base.html' %}
<!-- Overrides the base pageCustom block to include the tinyMCE rich text editor -->
{% block pageCustom %}
    <script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
{% endblock pageCustom %}
<!-- Overrides the base title block with the title of the page being edited -->
{% block title %}<title>Editing {{ page.page_name }}</title>{% endblock title %}
<!-- Overrides the content block with a form that displays the content of the page being edited and allows editing of its content -->
{% block content %}
    <!-- Header for reminding the user which page is being edited -->
    <h1> Editing {{ page.page_name }} </h1>

    <form method="post" action="{% url 'wiki:edit' page.page_name %}">
        <!-- Required CSRF token for security purposes -->
        {% csrf_token %}
        <!-- Displays the content of the page being edited and uses the 'safe' tag to allow displaying of HTML -->
        <div name="pagecontent" id="pagecontent">{{ page.page_content|safe }}</div>
        <!-- Cancel and save buttons for cancelling/saving edits -->
        <button type="submit" name="Cancel" value="Cancel">Cancel</button>
        <button type="submit" name="Save" value="Save">Save</button>

    </form>
    <!-- Overrides the base pageCustomScripts block to include a script for initialising tinyMCE -->
    {% block pageCustomScripts %}
        <script>tinymce.init({ selector:'#pagecontent', plugins: 'image' });</script>
    {% endblock pageCustomScripts %}

{% endblock content %}

wiki/templates/wiki/index.html
<!-- Extends the base template -->
{% extends 'wiki/base.html' %}
<!-- Overrides the base title block with the index title -->
{% block title %}<title>Index</title>{% endblock title %}
<!-- Overrides the base login block to add login/logout buttons -->
{% block login %}
    <!-- 'auth' determines if the user is authenticated; so, if the user is not, the 'login' nav is displayed -->
    {% if not auth %}
        <a href="{% url 'wiki:login' %}" class="btn btn-primary">Login</a>
    <!-- Else, if the user is authenticated, display the logout button -->
    {% else %}
        <a href="{% url 'wiki:logout' %}" class="btn btn-danger">Logout</a>
    {% endif %}
{% endblock login %}
<!-- Overrides the base content block to add an index of pages -->
{% block content %}
    <!-- If the context contains pages, -->
    {% if pages %}
        <!-- iterate through each page in the context, -->
        {% for page in pages %}
        <div class="container align-content-start">
            <ul>
                <!-- and display them in a list. -->
                <li class="list-group-item col-2">
                    <a href="{% url 'wiki:pageview' page.page_name %}">
                        {{ page.page_name }}
                    </a>
                </li>
            </ul>
        </div>
        {% endfor %}
    <!-- Else if no pages are in the context, notify the user that no pages are available -->
    {% else %}
        <p>No pages are available.</p>
    {% endif %}

{% endblock content %}

wiki/templates/wiki/login.html
<!-- Extends the base template -->
{% extends 'wiki/base.html' %}
<!-- Overrides the base title block with the login title -->
{% block title %}<title>Login</title>{% endblock title %}
<!-- Overrides the base content block to include a login form -->
{% block content %}
    <!-- If the user enters their details incorrectly, notify them -->
    {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
    {% endif %}
    <!-- If the page is going to redirect, -->
    {% if next %}
        <!-- check if the user is authenticated, -->
        {% if user.is_authenticated %}
            <!-- and notify them that their account does not have access to this page -->
            <p>Your account doesn't have access to this page. To proceed,
            please login with an account that has access.</p>
        <!-- Else, prompt the user to log in. -->
        {% else %}
            <p>Please login to see this page.</p>
        {% endif %}
    {% endif %}

    <form method="post" action="{% url 'wiki:login' %}">
        <!-- Required CSRF token for security purposes -->
        {% csrf_token %}
        <!-- Table containing rows for username and password labels and entry fields -->
        <table>
        <tr>
            <td>{{ form.username.label_tag }}</td>
            <td>{{ form.username }}</td>
        </tr>
        <tr>
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
        </tr>
        </table>
        <!-- Submit button for logging in -->
        <input type="submit" value="login" />
        <!-- If the page is going to redirect, [] -->
        {% if next %}
            <input type="hidden" name="next" value="{{ next }}" />
        {% else %}
            <input type="hidden" name="next" value="{% url 'wiki:index' %}">
        {% endif %}
    </form>

    <section>
        <p>Don't have an account?</p>
        <a href="{% url 'wiki:register' %}" class="btn btn-primary">Register</a>
    </section>

{% endblock content %}

wiki/templates/wiki/page.html
<!-- Extends the base template -->
{% extends 'wiki/base.html' %}
<!-- Retrieve template tags for use later -->
{% load wiki_tags %}
<!-- Overrides the base title block with this page's title -->
{% block title %}<title>{{ this_page.page_name }}</title>{% endblock title %}
<!-- Overrides the navItem block to add additional navbar items -->
{% block navItem %}
    <!-- Declares an 'edit page' button with a hyperlink reference to the current page's edit page -->
    <a class="btn btn-primary" href="{% url 'wiki:edit' pk=this_page.page_name %}">Edit Page</a>
{% endblock navItem %}
<!-- Overrides the base login block to add login/logout buttons -->
{% block login %}
    <!-- 'auth' determines if the user is authenticated; so, if the user is not, the 'login' nav is displayed -->
    {% if not auth %}
        <a href="{% url 'wiki:login' %}" class="btn btn-primary">Login</a>
    <!-- Else, if the user is authenticated, display the logout button -->
    {% else %}
        <a href="{% url 'wiki:logout' %}" class="btn btn-danger">Logout</a>
    {% endif %}
{% endblock login %}
<!-- Overrides the base content block to display a given page's content -->
{% block content %}
    <!-- The 'wikify' tag filters any text (which is also a page name) surrounded by two square brackets as a hyperlink -->
    <!-- The 'safe' tag allows users to enter HTML to be displayed on the web page -->
    {{ this_page.page_content|wikify|safe }}

    <footer class="footer">This page has been viewed {{ this_page.page_counter }} times.</footer>
{% endblock content %}

wiki/templates/wiki/upload.html
{% extends 'wiki/base.html' %}

{% block title %}<title>{{ this_page.page_name }}</title>{% endblock title %}

{% block content %}

    <section class="row justify-content-center">
        {% if files %}
            <ul class="m-3 list-group">
            {% for file in files %}
            <li class="list-group-item">
                <a href="{{ file.content.url }}">{{ file.displayname }}</a>
                <a class="btn btn-danger" href="{% url 'wiki:delete' file.pk %}">Delete</a>
            </li>
            {% endfor %}
            </ul>
        {% else %}
            <p>No uploaded files.</p>
        {% endif %}
    </section>

    <form method="POST" enctype="multipart/form-data" action="{% url 'wiki:upload' %}">
        {% csrf_token %}
        {{ form.content }}
        <input class="btn btn-success" type="submit" value="Upload">
    </form>

{% endblock content %}